import type { Metadata } from "next";
import Link from "next/link";
import { Inter } from "next/font/google";

import StoreProvider from "./providers/StoreProvider";

import "./globals.css";

const inter = Inter({
  subsets: ["latin"],
});

// serverComponent: Root layouts are Server Components by default.
// fileBasedRouting: layout.tsx defines the root layout.
// appDirectory: This layout is inside the app/ directory.
// metadata: Static metadata for the application.
// generateMetadata: Dynamic metadata can be generated by route pages.
// nextFont: Inter is loaded using next/font/google.
// fontOptimization: Next.js optimizes the font automatically.
// nextImage: Images used by the application are optimized with next/image.
// redux: Redux Toolkit provides global client-side state.
// StoreProvider: Provides Redux state to all Client Components.
// Provider: React Redux Provider wraps the application.
// configureStore: Redux Toolkit configures the application store.
// useSelector: Client Components use useSelector to read Redux state.
// useDispatch: Client Components use useDispatch to update Redux state.

export const metadata: Metadata = {
  title: "Next.js App Router Project",
  description: "Complete challenges to build your Next.js skills.",
  openGraph: {
    title: "Next.js App Router Project",
    description: "Complete challenges to build your Next.js skills.",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <StoreProvider>
          <nav>
            <Link href="/">Home</Link>
            {" | "}
            <Link href="/about">About</Link>
            {" | "}
            <Link href="/posts">Posts</Link>
          </nav>

          {children}
        </StoreProvider>
      </body>
    </html>
  );
}
