import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";

// serverComponent: Root layouts are Server Components by default.
// fileBasedRouting: layout.tsx defines the root layout.
// appDirectory: This layout is inside the app/ directory.
// useClient: The client boundary is isolated in Counter.tsx.
// useState: State belongs in the Client Component, not this layout.
// metadata: Static metadata for the application.
// title: Defines the browser page title.
// description: Defines the page description for SEO.
// generateMetadata: Dynamic metadata can be generated by route pages.

export const metadata: Metadata = {
  title: "Next.js App Router Project",
  description: "Complete challenges to build your Next.js skills",
  openGraph: {
    title: "Next.js App Router Project",
    description: "Complete challenges to build your Next.js skills",
  },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <nav>
          <Link href="/">Home</Link>
          {" | "}
          <Link href="/about">About</Link>
          {" | "}
          <Link href="/posts">Posts</Link>
        </nav>

        {children}
      </body>
    </html>
  );
}
